version: "3.8"
services:
  next:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      - socket
      - ratelimit
      - db
  socket:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: socket
    ports:
      - 5000:5000

    depends_on:
      - db
      - ratelimit
  ratelimit:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ยง{REDIS_REST_TOKEN}
    volumes:
      - ratelimit:/data

  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: message-board
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/my.cnf

volumes:
  mysql_data:
    driver: local
  ratelimit:
    driver: local
